"""add token columns to pdf_namings

Revision ID: 9210f15cb073
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 14:09:44.784721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9210f15cb073'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_namings', sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pdf_namings', sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_namings', 'output_tokens')
    op.drop_column('pdf_namings', 'input_tokens')
    # ### end Alembic commands ###
